/**
 * @file src/lib/zip-builder.ts
 * @description Generates client-side ZIP archives containing changed files
 * preserving folder structures and metadata documentation using JSZip with DEFLATE compression.
 */

import JSZip from 'jszip';
import { GitHubCommitDetail } from '../types/github';

/**
 * Builds and triggers browser download of a ZIP archive containing all changed files
 * from the selected commit along with a root COMMIT_INFO.md summary file.
 * 
 * @param repoName - Repository short name (e.g. 'react')
 * @param repoFullName - Full repository name (e.g. 'facebook/react')
 * @param branch - Branch name
 * @param commit - Full commit detail object with extracted file contents
 * @param includePreDeletion - Whether to include pre-deletion files in zip
 * @returns Promise that resolves when download is triggered
 */
export async function downloadCommitZip(
  repoName: string,
  repoFullName: string,
  branch: string,
  commit: GitHubCommitDetail,
  includePreDeletion: boolean = false
): Promise<void> {
  const zip = new JSZip();
  const shortSha = commit.sha.substring(0, 7);

  // 1. Generate COMMIT_INFO.md metadata file at zip root
  const commitInfoContent = [
    `# Commit Information`,
    ``,
    `- **Repository**: ${repoFullName}`,
    `- **Commit SHA**: ${commit.sha}`,
    `- **Branch**: ${branch}`,
    `- **Author**: ${commit.commit.author?.name} <${commit.commit.author?.email}>`,
    `- **Date**: ${commit.commit.author?.date}`,
    `- **Commit URL**: ${commit.html_url}`,
    `- **Stats**: +${commit.stats?.additions || 0} additions, -${commit.stats?.deletions || 0} deletions (${commit.files?.length || 0} files)`,
    ``,
    `## Commit Message`,
    `\`\`\``,
    commit.commit.message || '(no message)',
    `\`\`\``,
    ``,
    `## Included Files`,
    ...(commit.files || []).map(
      (f) => `- [${f.status.toUpperCase()}] \`${f.filename}\` (+${f.additions}/-${f.deletions})`
    ),
    ``,
    `---`,
    `Generated by CommitPack (GitHub Commit Inspector & AI Packager)`,
  ].join('\n');

  zip.file('COMMIT_INFO.md', commitInfoContent);

  // 2. Add each changed file preserving original directory structure
  (commit.files || []).forEach((file) => {
    if (file.status === 'removed') {
      if (includePreDeletion && file.preDeletionContent) {
        // Add pre-deletion version in a dedicated directory
        zip.file(`_pre_deletion/${file.filename}`, file.preDeletionContent);
      }
      return;
    }

    if (file.content !== undefined) {
      zip.file(file.filename, file.content);
    } else if (file.patch) {
      // Fallback: If full content not fetched, provide the patch as .diff
      zip.file(`${file.filename}.diff`, file.patch);
    }
  });

  // 3. Generate ZIP with DEFLATE level 9 compression
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: {
      level: 9,
    },
  });

  // 4. Trigger download
  const cleanRepoName = repoName.replace(/[^a-zA-Z0-9_\-]/g, '_');
  const filename = `${cleanRepoName}-${shortSha}-changed-files.zip`;

  const downloadUrl = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = downloadUrl;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(downloadUrl);
}
